// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISuperfluidPool$Type } from "./ISuperfluidPool";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISuperfluidPool"]: ISuperfluidPool$Type;
    ["@superfluid-finance/ethereum-contracts/contracts/interfaces/agreements/gdav1/ISuperfluidPool.sol:ISuperfluidPool"]: ISuperfluidPool$Type;
  }

  interface ContractTypesMap {
    ["ISuperfluidPool"]: GetContractReturnType<ISuperfluidPool$Type["abi"]>;
    ["@superfluid-finance/ethereum-contracts/contracts/interfaces/agreements/gdav1/ISuperfluidPool.sol:ISuperfluidPool"]: GetContractReturnType<ISuperfluidPool$Type["abi"]>;
  }
}
