// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IMinimalCFAv1$Type } from "./IMinimalCFAv1";
import { IMinimalCFAv1Read$Type } from "./IMinimalCFAv1Read";
import { IMinimalHost$Type } from "./IMinimalHost";
import { IMinimalSendEarnFactory$Type } from "./IMinimalSendEarnFactory";
import { SendEarnRewards$Type } from "./SendEarnRewards";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMinimalCFAv1"]: IMinimalCFAv1$Type;
    ["IMinimalCFAv1Read"]: IMinimalCFAv1Read$Type;
    ["IMinimalHost"]: IMinimalHost$Type;
    ["IMinimalSendEarnFactory"]: IMinimalSendEarnFactory$Type;
    ["SendEarnRewards"]: SendEarnRewards$Type;
    ["contracts/rewards/SendEarnRewards.sol:IMinimalCFAv1"]: IMinimalCFAv1$Type;
    ["contracts/rewards/SendEarnRewards.sol:IMinimalCFAv1Read"]: IMinimalCFAv1Read$Type;
    ["contracts/rewards/SendEarnRewards.sol:IMinimalHost"]: IMinimalHost$Type;
    ["contracts/rewards/SendEarnRewards.sol:IMinimalSendEarnFactory"]: IMinimalSendEarnFactory$Type;
    ["contracts/rewards/SendEarnRewards.sol:SendEarnRewards"]: SendEarnRewards$Type;
  }

  interface ContractTypesMap {
    ["IMinimalCFAv1"]: GetContractReturnType<IMinimalCFAv1$Type["abi"]>;
    ["IMinimalCFAv1Read"]: GetContractReturnType<IMinimalCFAv1Read$Type["abi"]>;
    ["IMinimalHost"]: GetContractReturnType<IMinimalHost$Type["abi"]>;
    ["IMinimalSendEarnFactory"]: GetContractReturnType<IMinimalSendEarnFactory$Type["abi"]>;
    ["SendEarnRewards"]: GetContractReturnType<SendEarnRewards$Type["abi"]>;
    ["contracts/rewards/SendEarnRewards.sol:IMinimalCFAv1"]: GetContractReturnType<IMinimalCFAv1$Type["abi"]>;
    ["contracts/rewards/SendEarnRewards.sol:IMinimalCFAv1Read"]: GetContractReturnType<IMinimalCFAv1Read$Type["abi"]>;
    ["contracts/rewards/SendEarnRewards.sol:IMinimalHost"]: GetContractReturnType<IMinimalHost$Type["abi"]>;
    ["contracts/rewards/SendEarnRewards.sol:IMinimalSendEarnFactory"]: GetContractReturnType<IMinimalSendEarnFactory$Type["abi"]>;
    ["contracts/rewards/SendEarnRewards.sol:SendEarnRewards"]: GetContractReturnType<SendEarnRewards$Type["abi"]>;
  }
}
