// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IMinimalHost$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IMinimalHost",
  "sourceName": "contracts/rewards/SendEarnRewards.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "agreementClass",
          "type": "address"
        },
        {
          "internalType": "bytes",
          "name": "callData",
          "type": "bytes"
        },
        {
          "internalType": "bytes",
          "name": "userData",
          "type": "bytes"
        }
      ],
      "name": "callAgreement",
      "outputs": [
        {
          "internalType": "bytes",
          "name": "returnedData",
          "type": "bytes"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "agreementType",
          "type": "bytes32"
        }
      ],
      "name": "getAgreementClass",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IMinimalHost",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMinimalHost$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/rewards/SendEarnRewards.sol:IMinimalHost",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMinimalHost$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IMinimalHost",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMinimalHost$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/rewards/SendEarnRewards.sol:IMinimalHost",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMinimalHost$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IMinimalHost",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMinimalHost$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/rewards/SendEarnRewards.sol:IMinimalHost",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMinimalHost$Type["abi"]>>;
}
