// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IMinimalCFAv1$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IMinimalCFAv1",
  "sourceName": "contracts/rewards/SendEarnRewards.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "token",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "receiver",
          "type": "address"
        },
        {
          "internalType": "int96",
          "name": "flowRate",
          "type": "int96"
        },
        {
          "internalType": "bytes",
          "name": "ctx",
          "type": "bytes"
        }
      ],
      "name": "createFlow",
      "outputs": [
        {
          "internalType": "bytes",
          "name": "newCtx",
          "type": "bytes"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "token",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "sender",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "receiver",
          "type": "address"
        },
        {
          "internalType": "bytes",
          "name": "ctx",
          "type": "bytes"
        }
      ],
      "name": "deleteFlow",
      "outputs": [
        {
          "internalType": "bytes",
          "name": "newCtx",
          "type": "bytes"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "token",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "receiver",
          "type": "address"
        },
        {
          "internalType": "int96",
          "name": "flowRate",
          "type": "int96"
        },
        {
          "internalType": "bytes",
          "name": "ctx",
          "type": "bytes"
        }
      ],
      "name": "updateFlow",
      "outputs": [
        {
          "internalType": "bytes",
          "name": "newCtx",
          "type": "bytes"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IMinimalCFAv1",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMinimalCFAv1$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/rewards/SendEarnRewards.sol:IMinimalCFAv1",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMinimalCFAv1$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IMinimalCFAv1",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMinimalCFAv1$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/rewards/SendEarnRewards.sol:IMinimalCFAv1",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMinimalCFAv1$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IMinimalCFAv1",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMinimalCFAv1$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/rewards/SendEarnRewards.sol:IMinimalCFAv1",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMinimalCFAv1$Type["abi"]>>;
}
