// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC4626$Type } from "./ERC4626";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC4626"]: ERC4626$Type;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC4626.sol:ERC4626"]: ERC4626$Type;
  }

  interface ContractTypesMap {
    ["ERC4626"]: GetContractReturnType<ERC4626$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC4626.sol:ERC4626"]: GetContractReturnType<ERC4626$Type["abi"]>;
  }
}
