// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IGeneralDistributionAgreementV1$Type } from "./IGeneralDistributionAgreementV1";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IGeneralDistributionAgreementV1"]: IGeneralDistributionAgreementV1$Type;
    ["@superfluid-finance/ethereum-contracts/contracts/interfaces/agreements/gdav1/IGeneralDistributionAgreementV1.sol:IGeneralDistributionAgreementV1"]: IGeneralDistributionAgreementV1$Type;
  }

  interface ContractTypesMap {
    ["IGeneralDistributionAgreementV1"]: GetContractReturnType<IGeneralDistributionAgreementV1$Type["abi"]>;
    ["@superfluid-finance/ethereum-contracts/contracts/interfaces/agreements/gdav1/IGeneralDistributionAgreementV1.sol:IGeneralDistributionAgreementV1"]: GetContractReturnType<IGeneralDistributionAgreementV1$Type["abi"]>;
  }
}
