// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC4626TestVault$Type } from "./ERC4626TestVault";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC4626TestVault"]: ERC4626TestVault$Type;
    ["contracts/mocks/MinimalVault.sol:ERC4626TestVault"]: ERC4626TestVault$Type;
  }

  interface ContractTypesMap {
    ["ERC4626TestVault"]: GetContractReturnType<ERC4626TestVault$Type["abi"]>;
    ["contracts/mocks/MinimalVault.sol:ERC4626TestVault"]: GetContractReturnType<ERC4626TestVault$Type["abi"]>;
  }
}
