// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CFAMock$Type } from "./CFAMock";
import { HostMock$Type } from "./HostMock";
import { IMinimalCFAv1Like$Type } from "./IMinimalCFAv1Like";
import { IMinimalCFAv1ReadLike$Type } from "./IMinimalCFAv1ReadLike";
import { SuperTokenMock$Type } from "./SuperTokenMock";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CFAMock"]: CFAMock$Type;
    ["HostMock"]: HostMock$Type;
    ["IMinimalCFAv1Like"]: IMinimalCFAv1Like$Type;
    ["IMinimalCFAv1ReadLike"]: IMinimalCFAv1ReadLike$Type;
    ["SuperTokenMock"]: SuperTokenMock$Type;
    ["contracts/mocks/SuperfluidCFAHostMocks.sol:CFAMock"]: CFAMock$Type;
    ["contracts/mocks/SuperfluidCFAHostMocks.sol:HostMock"]: HostMock$Type;
    ["contracts/mocks/SuperfluidCFAHostMocks.sol:IMinimalCFAv1Like"]: IMinimalCFAv1Like$Type;
    ["contracts/mocks/SuperfluidCFAHostMocks.sol:IMinimalCFAv1ReadLike"]: IMinimalCFAv1ReadLike$Type;
    ["contracts/mocks/SuperfluidCFAHostMocks.sol:SuperTokenMock"]: SuperTokenMock$Type;
  }

  interface ContractTypesMap {
    ["CFAMock"]: GetContractReturnType<CFAMock$Type["abi"]>;
    ["HostMock"]: GetContractReturnType<HostMock$Type["abi"]>;
    ["IMinimalCFAv1Like"]: GetContractReturnType<IMinimalCFAv1Like$Type["abi"]>;
    ["IMinimalCFAv1ReadLike"]: GetContractReturnType<IMinimalCFAv1ReadLike$Type["abi"]>;
    ["SuperTokenMock"]: GetContractReturnType<SuperTokenMock$Type["abi"]>;
    ["contracts/mocks/SuperfluidCFAHostMocks.sol:CFAMock"]: GetContractReturnType<CFAMock$Type["abi"]>;
    ["contracts/mocks/SuperfluidCFAHostMocks.sol:HostMock"]: GetContractReturnType<HostMock$Type["abi"]>;
    ["contracts/mocks/SuperfluidCFAHostMocks.sol:IMinimalCFAv1Like"]: GetContractReturnType<IMinimalCFAv1Like$Type["abi"]>;
    ["contracts/mocks/SuperfluidCFAHostMocks.sol:IMinimalCFAv1ReadLike"]: GetContractReturnType<IMinimalCFAv1ReadLike$Type["abi"]>;
    ["contracts/mocks/SuperfluidCFAHostMocks.sol:SuperTokenMock"]: GetContractReturnType<SuperTokenMock$Type["abi"]>;
  }
}
