// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IMinimalCFAv1ReadLike$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IMinimalCFAv1ReadLike",
  "sourceName": "contracts/mocks/SuperfluidCFAHostMocks.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "token",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "sender",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "receiver",
          "type": "address"
        }
      ],
      "name": "getFlow",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        },
        {
          "internalType": "int96",
          "name": "",
          "type": "int96"
        },
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IMinimalCFAv1ReadLike",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMinimalCFAv1ReadLike$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/mocks/SuperfluidCFAHostMocks.sol:IMinimalCFAv1ReadLike",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMinimalCFAv1ReadLike$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IMinimalCFAv1ReadLike",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMinimalCFAv1ReadLike$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/mocks/SuperfluidCFAHostMocks.sol:IMinimalCFAv1ReadLike",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMinimalCFAv1ReadLike$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IMinimalCFAv1ReadLike",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMinimalCFAv1ReadLike$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/mocks/SuperfluidCFAHostMocks.sol:IMinimalCFAv1ReadLike",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMinimalCFAv1ReadLike$Type["abi"]>>;
}
