// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { AbiParameterToPrimitiveType, GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SuperTokenMock$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SuperTokenMock",
  "sourceName": "contracts/mocks/SuperfluidCFAHostMocks.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_host",
          "type": "address"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "inputs": [],
      "name": "getHost",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "host",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x608060405234801561001057600080fd5b5060405161026d38038061026d833981810160405281019061003291906100db565b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050610108565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100a88261007d565b9050919050565b6100b88161009d565b81146100c357600080fd5b50565b6000815190506100d5816100af565b92915050565b6000602082840312156100f1576100f0610078565b5b60006100ff848285016100c6565b91505092915050565b610156806101176000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806320bc44251461003b578063f437bc5914610059575b600080fd5b610043610077565b6040516100509190610105565b60405180910390f35b6100616100a0565b60405161006e9190610105565b60405180910390f35b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905090565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100ef826100c4565b9050919050565b6100ff816100e4565b82525050565b600060208201905061011a60008301846100f6565b9291505056fea264697066735822122081d91245fc776daba03559134159e80f5583e2d3d17a6c5cc6e61d37409ef09f64736f6c634300081c0033",
  "deployedBytecode": "0x608060405234801561001057600080fd5b50600436106100365760003560e01c806320bc44251461003b578063f437bc5914610059575b600080fd5b610043610077565b6040516100509190610105565b60405180910390f35b6100616100a0565b60405161006e9190610105565b60405180910390f35b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905090565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100ef826100c4565b9050919050565b6100ff816100e4565b82525050565b600060208201905061011a60008301846100f6565b9291505056fea264697066735822122081d91245fc776daba03559134159e80f5583e2d3d17a6c5cc6e61d37409ef09f64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SuperTokenMock",
    constructorArgs: [_host: AbiParameterToPrimitiveType<{"name":"_host","type":"address"}>],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SuperTokenMock$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/mocks/SuperfluidCFAHostMocks.sol:SuperTokenMock",
    constructorArgs: [_host: AbiParameterToPrimitiveType<{"name":"_host","type":"address"}>],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SuperTokenMock$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SuperTokenMock",
    constructorArgs: [_host: AbiParameterToPrimitiveType<{"name":"_host","type":"address"}>],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SuperTokenMock$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/mocks/SuperfluidCFAHostMocks.sol:SuperTokenMock",
    constructorArgs: [_host: AbiParameterToPrimitiveType<{"name":"_host","type":"address"}>],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SuperTokenMock$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SuperTokenMock",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SuperTokenMock$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/mocks/SuperfluidCFAHostMocks.sol:SuperTokenMock",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SuperTokenMock$Type["abi"]>>;
}
