// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISuperfluidToken$Type } from "./ISuperfluidToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISuperfluidToken"]: ISuperfluidToken$Type;
    ["@superfluid-finance/ethereum-contracts/contracts/interfaces/superfluid/ISuperfluidToken.sol:ISuperfluidToken"]: ISuperfluidToken$Type;
  }

  interface ContractTypesMap {
    ["ISuperfluidToken"]: GetContractReturnType<ISuperfluidToken$Type["abi"]>;
    ["@superfluid-finance/ethereum-contracts/contracts/interfaces/superfluid/ISuperfluidToken.sol:ISuperfluidToken"]: GetContractReturnType<ISuperfluidToken$Type["abi"]>;
  }
}
