// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IMinimalSendEarnFactoryLike$Type } from "./IMinimalSendEarnFactoryLike";
import { SendEarnFactoryMock$Type } from "./SendEarnFactoryMock";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMinimalSendEarnFactoryLike"]: IMinimalSendEarnFactoryLike$Type;
    ["SendEarnFactoryMock"]: SendEarnFactoryMock$Type;
    ["contracts/mocks/SendEarnFactoryMock.sol:IMinimalSendEarnFactoryLike"]: IMinimalSendEarnFactoryLike$Type;
    ["contracts/mocks/SendEarnFactoryMock.sol:SendEarnFactoryMock"]: SendEarnFactoryMock$Type;
  }

  interface ContractTypesMap {
    ["IMinimalSendEarnFactoryLike"]: GetContractReturnType<IMinimalSendEarnFactoryLike$Type["abi"]>;
    ["SendEarnFactoryMock"]: GetContractReturnType<SendEarnFactoryMock$Type["abi"]>;
    ["contracts/mocks/SendEarnFactoryMock.sol:IMinimalSendEarnFactoryLike"]: GetContractReturnType<IMinimalSendEarnFactoryLike$Type["abi"]>;
    ["contracts/mocks/SendEarnFactoryMock.sol:SendEarnFactoryMock"]: GetContractReturnType<SendEarnFactoryMock$Type["abi"]>;
  }
}
