// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SendEarnFactoryMock$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SendEarnFactoryMock",
  "sourceName": "contracts/mocks/SendEarnFactoryMock.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "name": "isSendEarn",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "target",
          "type": "address"
        },
        {
          "internalType": "bool",
          "name": "allowed",
          "type": "bool"
        }
      ],
      "name": "setIsSendEarn",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x6080604052348015600f57600080fd5b506102698061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063464d225a1461003b578063c53576691461006b575b600080fd5b61005560048036038101906100509190610164565b610087565b60405161006291906101ac565b60405180910390f35b610085600480360381019061008091906101f3565b6100a7565b005b60006020528060005260406000206000915054906101000a900460ff1681565b806000808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff0219169083151502179055505050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061013182610106565b9050919050565b61014181610126565b811461014c57600080fd5b50565b60008135905061015e81610138565b92915050565b60006020828403121561017a57610179610101565b5b60006101888482850161014f565b91505092915050565b60008115159050919050565b6101a681610191565b82525050565b60006020820190506101c1600083018461019d565b92915050565b6101d081610191565b81146101db57600080fd5b50565b6000813590506101ed816101c7565b92915050565b6000806040838503121561020a57610209610101565b5b60006102188582860161014f565b9250506020610229858286016101de565b915050925092905056fea2646970667358221220a5e5d601c2ecab8cace2136774d1f7811080dc099400df875f24a73d31f66a8c64736f6c634300081c0033",
  "deployedBytecode": "0x608060405234801561001057600080fd5b50600436106100365760003560e01c8063464d225a1461003b578063c53576691461006b575b600080fd5b61005560048036038101906100509190610164565b610087565b60405161006291906101ac565b60405180910390f35b610085600480360381019061008091906101f3565b6100a7565b005b60006020528060005260406000206000915054906101000a900460ff1681565b806000808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff0219169083151502179055505050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061013182610106565b9050919050565b61014181610126565b811461014c57600080fd5b50565b60008135905061015e81610138565b92915050565b60006020828403121561017a57610179610101565b5b60006101888482850161014f565b91505092915050565b60008115159050919050565b6101a681610191565b82525050565b60006020820190506101c1600083018461019d565b92915050565b6101d081610191565b81146101db57600080fd5b50565b6000813590506101ed816101c7565b92915050565b6000806040838503121561020a57610209610101565b5b60006102188582860161014f565b9250506020610229858286016101de565b915050925092905056fea2646970667358221220a5e5d601c2ecab8cace2136774d1f7811080dc099400df875f24a73d31f66a8c64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SendEarnFactoryMock",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SendEarnFactoryMock$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/mocks/SendEarnFactoryMock.sol:SendEarnFactoryMock",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SendEarnFactoryMock$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SendEarnFactoryMock",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SendEarnFactoryMock$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/mocks/SendEarnFactoryMock.sol:SendEarnFactoryMock",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SendEarnFactoryMock$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SendEarnFactoryMock",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SendEarnFactoryMock$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/mocks/SendEarnFactoryMock.sol:SendEarnFactoryMock",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SendEarnFactoryMock$Type["abi"]>>;
}
