// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IMinimalSendEarnFactory$Type } from "./IMinimalSendEarnFactory";
import { IMinimalSuperfluid$Type } from "./IMinimalSuperfluid";
import { RewardsManager$Type } from "./RewardsManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMinimalSendEarnFactory"]: IMinimalSendEarnFactory$Type;
    ["IMinimalSuperfluid"]: IMinimalSuperfluid$Type;
    ["RewardsManager"]: RewardsManager$Type;
    ["contracts/rewards/RewardsManager.sol:IMinimalSendEarnFactory"]: IMinimalSendEarnFactory$Type;
    ["contracts/rewards/RewardsManager.sol:IMinimalSuperfluid"]: IMinimalSuperfluid$Type;
    ["contracts/rewards/RewardsManager.sol:RewardsManager"]: RewardsManager$Type;
  }

  interface ContractTypesMap {
    ["IMinimalSendEarnFactory"]: GetContractReturnType<IMinimalSendEarnFactory$Type["abi"]>;
    ["IMinimalSuperfluid"]: GetContractReturnType<IMinimalSuperfluid$Type["abi"]>;
    ["RewardsManager"]: GetContractReturnType<RewardsManager$Type["abi"]>;
    ["contracts/rewards/RewardsManager.sol:IMinimalSendEarnFactory"]: GetContractReturnType<IMinimalSendEarnFactory$Type["abi"]>;
    ["contracts/rewards/RewardsManager.sol:IMinimalSuperfluid"]: GetContractReturnType<IMinimalSuperfluid$Type["abi"]>;
    ["contracts/rewards/RewardsManager.sol:RewardsManager"]: GetContractReturnType<RewardsManager$Type["abi"]>;
  }
}
