// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IMinimalSuperfluid$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IMinimalSuperfluid",
  "sourceName": "contracts/rewards/RewardsManager.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "agreementType",
          "type": "bytes32"
        }
      ],
      "name": "getAgreementClass",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IMinimalSuperfluid",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMinimalSuperfluid$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/rewards/RewardsManager.sol:IMinimalSuperfluid",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMinimalSuperfluid$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IMinimalSuperfluid",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMinimalSuperfluid$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/rewards/RewardsManager.sol:IMinimalSuperfluid",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMinimalSuperfluid$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IMinimalSuperfluid",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMinimalSuperfluid$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/rewards/RewardsManager.sol:IMinimalSuperfluid",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMinimalSuperfluid$Type["abi"]>>;
}
