// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IMinimalSendEarnFactory$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IMinimalSendEarnFactory",
  "sourceName": "contracts/rewards/RewardsManager.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "affiliate",
          "type": "address"
        }
      ],
      "name": "affiliates",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "target",
          "type": "address"
        }
      ],
      "name": "isSendEarn",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "contracts/rewards/RewardsManager.sol:IMinimalSendEarnFactory",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMinimalSendEarnFactory$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "contracts/rewards/RewardsManager.sol:IMinimalSendEarnFactory",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMinimalSendEarnFactory$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "contracts/rewards/RewardsManager.sol:IMinimalSendEarnFactory",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMinimalSendEarnFactory$Type["abi"]>>;
}
