// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IMinimalSuperTokenFactory$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IMinimalSuperTokenFactory",
  "sourceName": "contracts/rewards/RewardsManager.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "underlyingToken",
          "type": "address"
        },
        {
          "internalType": "uint8",
          "name": "underlyingDecimals",
          "type": "uint8"
        },
        {
          "internalType": "uint8",
          "name": "upgradability",
          "type": "uint8"
        },
        {
          "internalType": "string",
          "name": "name",
          "type": "string"
        },
        {
          "internalType": "string",
          "name": "symbol",
          "type": "string"
        }
      ],
      "name": "createERC20Wrapper",
      "outputs": [
        {
          "internalType": "address",
          "name": "superToken",
          "type": "address"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "underlyingToken",
          "type": "address"
        }
      ],
      "name": "getCanonicalERC20Wrapper",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IMinimalSuperTokenFactory",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMinimalSuperTokenFactory$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/rewards/RewardsManager.sol:IMinimalSuperTokenFactory",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IMinimalSuperTokenFactory$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IMinimalSuperTokenFactory",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMinimalSuperTokenFactory$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/rewards/RewardsManager.sol:IMinimalSuperTokenFactory",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IMinimalSuperTokenFactory$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IMinimalSuperTokenFactory",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMinimalSuperTokenFactory$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/rewards/RewardsManager.sol:IMinimalSuperTokenFactory",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IMinimalSuperTokenFactory$Type["abi"]>>;
}
