// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IMinimalSendEarnFactory$Type } from "./IMinimalSendEarnFactory";
import { MockSendEarnFactory$Type } from "./MockSendEarnFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IMinimalSendEarnFactory"]: IMinimalSendEarnFactory$Type;
    ["MockSendEarnFactory"]: MockSendEarnFactory$Type;
    ["contracts/mocks/MockSendEarnFactory.sol:IMinimalSendEarnFactory"]: IMinimalSendEarnFactory$Type;
    ["contracts/mocks/MockSendEarnFactory.sol:MockSendEarnFactory"]: MockSendEarnFactory$Type;
  }

  interface ContractTypesMap {
    ["IMinimalSendEarnFactory"]: GetContractReturnType<IMinimalSendEarnFactory$Type["abi"]>;
    ["MockSendEarnFactory"]: GetContractReturnType<MockSendEarnFactory$Type["abi"]>;
    ["contracts/mocks/MockSendEarnFactory.sol:IMinimalSendEarnFactory"]: GetContractReturnType<IMinimalSendEarnFactory$Type["abi"]>;
    ["contracts/mocks/MockSendEarnFactory.sol:MockSendEarnFactory"]: GetContractReturnType<MockSendEarnFactory$Type["abi"]>;
  }
}
