// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISuperAgreement$Type } from "./ISuperAgreement";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISuperAgreement"]: ISuperAgreement$Type;
    ["@superfluid-finance/ethereum-contracts/contracts/interfaces/superfluid/ISuperAgreement.sol:ISuperAgreement"]: ISuperAgreement$Type;
  }

  interface ContractTypesMap {
    ["ISuperAgreement"]: GetContractReturnType<ISuperAgreement$Type["abi"]>;
    ["@superfluid-finance/ethereum-contracts/contracts/interfaces/superfluid/ISuperAgreement.sol:ISuperAgreement"]: GetContractReturnType<ISuperAgreement$Type["abi"]>;
  }
}
