// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ISuperAgreement$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ISuperAgreement",
  "sourceName": "@superfluid-finance/ethereum-contracts/contracts/interfaces/superfluid/ISuperAgreement.sol",
  "abi": [
    {
      "inputs": [],
      "name": "agreementType",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "contract ISuperfluidToken",
          "name": "token",
          "type": "address"
        },
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "time",
          "type": "uint256"
        }
      ],
      "name": "realtimeBalanceOf",
      "outputs": [
        {
          "internalType": "int256",
          "name": "dynamicBalance",
          "type": "int256"
        },
        {
          "internalType": "uint256",
          "name": "deposit",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "owedDeposit",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ISuperAgreement",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISuperAgreement$Type["abi"]>>;
  export function deployContract(
    contractName: "@superfluid-finance/ethereum-contracts/contracts/interfaces/superfluid/ISuperAgreement.sol:ISuperAgreement",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISuperAgreement$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ISuperAgreement",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISuperAgreement$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@superfluid-finance/ethereum-contracts/contracts/interfaces/superfluid/ISuperAgreement.sol:ISuperAgreement",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISuperAgreement$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ISuperAgreement",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISuperAgreement$Type["abi"]>>;
  export function getContractAt(
    contractName: "@superfluid-finance/ethereum-contracts/contracts/interfaces/superfluid/ISuperAgreement.sol:ISuperAgreement",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISuperAgreement$Type["abi"]>>;
}
