// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC4626$Type } from "./IERC4626";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC4626"]: IERC4626$Type;
    ["@openzeppelin/contracts/interfaces/IERC4626.sol:IERC4626"]: IERC4626$Type;
  }

  interface ContractTypesMap {
    ["IERC4626"]: GetContractReturnType<IERC4626$Type["abi"]>;
    ["@openzeppelin/contracts/interfaces/IERC4626.sol:IERC4626"]: GetContractReturnType<IERC4626$Type["abi"]>;
  }
}
