// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC4626Minimal$Type } from "./IERC4626Minimal";
import { MockERC4626Vault$Type } from "./MockERC4626Vault";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC4626Minimal"]: IERC4626Minimal$Type;
    ["MockERC4626Vault"]: MockERC4626Vault$Type;
    ["contracts/mocks/MockERC4626Vault.sol:IERC4626Minimal"]: IERC4626Minimal$Type;
    ["contracts/mocks/MockERC4626Vault.sol:MockERC4626Vault"]: MockERC4626Vault$Type;
  }

  interface ContractTypesMap {
    ["IERC4626Minimal"]: GetContractReturnType<IERC4626Minimal$Type["abi"]>;
    ["MockERC4626Vault"]: GetContractReturnType<MockERC4626Vault$Type["abi"]>;
    ["contracts/mocks/MockERC4626Vault.sol:IERC4626Minimal"]: GetContractReturnType<IERC4626Minimal$Type["abi"]>;
    ["contracts/mocks/MockERC4626Vault.sol:MockERC4626Vault"]: GetContractReturnType<MockERC4626Vault$Type["abi"]>;
  }
}
