// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IERC4626Minimal$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IERC4626Minimal",
  "sourceName": "contracts/mocks/MockERC4626Vault.sol",
  "abi": [
    {
      "inputs": [],
      "name": "asset",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "account",
          "type": "address"
        }
      ],
      "name": "balanceOf",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "shares",
          "type": "uint256"
        }
      ],
      "name": "convertToAssets",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IERC4626Minimal",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IERC4626Minimal$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/mocks/MockERC4626Vault.sol:IERC4626Minimal",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IERC4626Minimal$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IERC4626Minimal",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IERC4626Minimal$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/mocks/MockERC4626Vault.sol:IERC4626Minimal",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IERC4626Minimal$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IERC4626Minimal",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IERC4626Minimal$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/mocks/MockERC4626Vault.sol:IERC4626Minimal",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IERC4626Minimal$Type["abi"]>>;
}
